#!/usr/bin/with-contenv bash

set -euo pipefail

# Cleanup data
rm -fr /tmp/data ~/.synapseConfig

if [ ! -d "/tmp/data" ]; then
    # Create ~/.synapseConfig
    printf "%s\n" \
        "[authentication]" \
        "username = ${SYNAPSE_USERNAME}" \
        "apikey = ${SYNAPSE_API_KEY}" | tee -a ~/.synapseConfig >/dev/null

    mkdir -p /tmp/data

   # Download clinical notes from Synapse
    synapse get ${DATA_SYNAPSE_ID} --downloadLocation /tmp/data \
        >/dev/null
    echo ${DATA_MD5} \
        /tmp/data/2014-i2b2-nlp-evaluation-data-txt.zip | md5sum --check - \
        >/dev/null
    unzip /tmp/data/2014-i2b2-nlp-evaluation-data-txt.zip \
        -d /tmp/data \
        >/dev/null
    rm -fr /tmp/data/2014-i2b2-nlp-evaluation-data-txt.zip

    # Download goldstandard annotations from Synapse
    synapse get ${GOLDSTANDARD_SYNAPSE_ID} --downloadLocation /tmp/data \
        >/dev/null
    echo ${GOLDSTANDARD_MD5} \
        /tmp/data/official-testing-PHI-Gold-fixed.tar.gz | md5sum --check - \
        >/dev/null
    tar xvf /tmp/data/official-testing-PHI-Gold-fixed.tar.gz \
        --directory /tmp/data \
        >/dev/null
    rm -fr /tmp/data/official-testing-PHI-Gold-fixed.tar.gz
fi

