# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.resource_source import ResourceSource
from openapi_server import util

from openapi_server.models.resource_source import ResourceSource  # noqa: E501

class AnnotationSource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, resource_source=None):  # noqa: E501
        """AnnotationSource - a model defined in OpenAPI

        :param resource_source: The resource_source of this AnnotationSource.  # noqa: E501
        :type resource_source: ResourceSource
        """
        self.openapi_types = {
            'resource_source': ResourceSource
        }

        self.attribute_map = {
            'resource_source': 'resourceSource'
        }

        self._resource_source = resource_source

    @classmethod
    def from_dict(cls, dikt) -> 'AnnotationSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnnotationSource of this AnnotationSource.  # noqa: E501
        :rtype: AnnotationSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_source(self):
        """Gets the resource_source of this AnnotationSource.


        :return: The resource_source of this AnnotationSource.
        :rtype: ResourceSource
        """
        return self._resource_source

    @resource_source.setter
    def resource_source(self, resource_source):
        """Sets the resource_source of this AnnotationSource.


        :param resource_source: The resource_source of this AnnotationSource.
        :type resource_source: ResourceSource
        """

        self._resource_source = resource_source
