# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.page_response_links import PageResponseLinks
from openapi_server import util

from openapi_server.models.page_response_links import PageResponseLinks  # noqa: E501

class PageResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, links=None):  # noqa: E501
        """PageResponse - a model defined in OpenAPI

        :param links: The links of this PageResponse.  # noqa: E501
        :type links: PageResponseLinks
        """
        self.openapi_types = {
            'links': PageResponseLinks
        }

        self.attribute_map = {
            'links': 'links'
        }

        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'PageResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageResponse of this PageResponse.  # noqa: E501
        :rtype: PageResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self):
        """Gets the links of this PageResponse.


        :return: The links of this PageResponse.
        :rtype: PageResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PageResponse.


        :param links: The links of this PageResponse.
        :type links: PageResponseLinks
        """

        self._links = links
