# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.annotation_store import AnnotationStore
from openapi_server import util

from openapi_server.models.annotation_store import AnnotationStore  # noqa: E501

class PageOfAnnotationStoresAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """PageOfAnnotationStoresAllOf - a model defined in OpenAPI

        :param items: The items of this PageOfAnnotationStoresAllOf.  # noqa: E501
        :type items: List[AnnotationStore]
        """
        self.openapi_types = {
            'items': List[AnnotationStore]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfAnnotationStoresAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfAnnotationStores_allOf of this PageOfAnnotationStoresAllOf.  # noqa: E501
        :rtype: PageOfAnnotationStoresAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this PageOfAnnotationStoresAllOf.

        An array of annotation stores  # noqa: E501

        :return: The items of this PageOfAnnotationStoresAllOf.
        :rtype: List[AnnotationStore]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PageOfAnnotationStoresAllOf.

        An array of annotation stores  # noqa: E501

        :param items: The items of this PageOfAnnotationStoresAllOf.
        :type items: List[AnnotationStore]
        """

        self._items = items
