# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.page_of_patients_all_of import PageOfPatientsAllOf
from openapi_server.models.page_response import PageResponse
from openapi_server.models.page_response_links import PageResponseLinks
from openapi_server.models.patient import Patient
from openapi_server import util

from openapi_server.models.page_of_patients_all_of import PageOfPatientsAllOf  # noqa: E501
from openapi_server.models.page_response import PageResponse  # noqa: E501
from openapi_server.models.page_response_links import PageResponseLinks  # noqa: E501
from openapi_server.models.patient import Patient  # noqa: E501

class PageOfPatients(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=None, limit=None, links=None, patients=None):  # noqa: E501
        """PageOfPatients - a model defined in OpenAPI

        :param offset: The offset of this PageOfPatients.  # noqa: E501
        :type offset: int
        :param limit: The limit of this PageOfPatients.  # noqa: E501
        :type limit: int
        :param links: The links of this PageOfPatients.  # noqa: E501
        :type links: PageResponseLinks
        :param patients: The patients of this PageOfPatients.  # noqa: E501
        :type patients: List[Patient]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'links': PageResponseLinks,
            'patients': List[Patient]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'links': 'links',
            'patients': 'patients'
        }

        self._offset = offset
        self._limit = limit
        self._links = links
        self._patients = patients

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfPatients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfPatients of this PageOfPatients.  # noqa: E501
        :rtype: PageOfPatients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this PageOfPatients.

        Index of the first result that must be returned  # noqa: E501

        :return: The offset of this PageOfPatients.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PageOfPatients.

        Index of the first result that must be returned  # noqa: E501

        :param offset: The offset of this PageOfPatients.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this PageOfPatients.

        Maximum number of results returned  # noqa: E501

        :return: The limit of this PageOfPatients.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PageOfPatients.

        Maximum number of results returned  # noqa: E501

        :param limit: The limit of this PageOfPatients.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def links(self):
        """Gets the links of this PageOfPatients.


        :return: The links of this PageOfPatients.
        :rtype: PageResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PageOfPatients.


        :param links: The links of this PageOfPatients.
        :type links: PageResponseLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def patients(self):
        """Gets the patients of this PageOfPatients.

        An array of FHIR Patients  # noqa: E501

        :return: The patients of this PageOfPatients.
        :rtype: List[Patient]
        """
        return self._patients

    @patients.setter
    def patients(self, patients):
        """Sets the patients of this PageOfPatients.

        An array of FHIR Patients  # noqa: E501

        :param patients: The patients of this PageOfPatients.
        :type patients: List[Patient]
        """

        self._patients = patients
