# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.annotation_store import AnnotationStore
from openapi_server.models.response_page_metadata import ResponsePageMetadata
from openapi_server.models.response_page_metadata_links import ResponsePageMetadataLinks
from openapi_server import util

from openapi_server.models.annotation_store import AnnotationStore  # noqa: E501
from openapi_server.models.response_page_metadata import ResponsePageMetadata  # noqa: E501
from openapi_server.models.response_page_metadata_links import ResponsePageMetadataLinks  # noqa: E501

class PageOfAnnotationStores(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=0, limit=10, links=None, total_results=None, annotation_stores=None):  # noqa: E501
        """PageOfAnnotationStores - a model defined in OpenAPI

        :param offset: The offset of this PageOfAnnotationStores.  # noqa: E501
        :type offset: int
        :param limit: The limit of this PageOfAnnotationStores.  # noqa: E501
        :type limit: int
        :param links: The links of this PageOfAnnotationStores.  # noqa: E501
        :type links: ResponsePageMetadataLinks
        :param total_results: The total_results of this PageOfAnnotationStores.  # noqa: E501
        :type total_results: int
        :param annotation_stores: The annotation_stores of this PageOfAnnotationStores.  # noqa: E501
        :type annotation_stores: List[AnnotationStore]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'links': ResponsePageMetadataLinks,
            'total_results': int,
            'annotation_stores': List[AnnotationStore]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'links': 'links',
            'total_results': 'totalResults',
            'annotation_stores': 'annotationStores'
        }

        self._offset = offset
        self._limit = limit
        self._links = links
        self._total_results = total_results
        self._annotation_stores = annotation_stores

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfAnnotationStores':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfAnnotationStores of this PageOfAnnotationStores.  # noqa: E501
        :rtype: PageOfAnnotationStores
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this PageOfAnnotationStores.

        The index of the first result that must be returned  # noqa: E501

        :return: The offset of this PageOfAnnotationStores.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PageOfAnnotationStores.

        The index of the first result that must be returned  # noqa: E501

        :param offset: The offset of this PageOfAnnotationStores.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501
        if offset is not None and offset < 0:  # noqa: E501
            raise ValueError("Invalid value for `offset`, must be a value greater than or equal to `0`")  # noqa: E501

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this PageOfAnnotationStores.

        The maximum number of results returned  # noqa: E501

        :return: The limit of this PageOfAnnotationStores.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PageOfAnnotationStores.

        The maximum number of results returned  # noqa: E501

        :param limit: The limit of this PageOfAnnotationStores.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501
        if limit is not None and limit > 100:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `100`")  # noqa: E501
        if limit is not None and limit < 10:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `10`")  # noqa: E501

        self._limit = limit

    @property
    def links(self):
        """Gets the links of this PageOfAnnotationStores.


        :return: The links of this PageOfAnnotationStores.
        :rtype: ResponsePageMetadataLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PageOfAnnotationStores.


        :param links: The links of this PageOfAnnotationStores.
        :type links: ResponsePageMetadataLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def total_results(self):
        """Gets the total_results of this PageOfAnnotationStores.

        Total number of results in the result set  # noqa: E501

        :return: The total_results of this PageOfAnnotationStores.
        :rtype: int
        """
        return self._total_results

    @total_results.setter
    def total_results(self, total_results):
        """Sets the total_results of this PageOfAnnotationStores.

        Total number of results in the result set  # noqa: E501

        :param total_results: The total_results of this PageOfAnnotationStores.
        :type total_results: int
        """
        if total_results is None:
            raise ValueError("Invalid value for `total_results`, must not be `None`")  # noqa: E501

        self._total_results = total_results

    @property
    def annotation_stores(self):
        """Gets the annotation_stores of this PageOfAnnotationStores.

        An array of annotation stores  # noqa: E501

        :return: The annotation_stores of this PageOfAnnotationStores.
        :rtype: List[AnnotationStore]
        """
        return self._annotation_stores

    @annotation_stores.setter
    def annotation_stores(self, annotation_stores):
        """Sets the annotation_stores of this PageOfAnnotationStores.

        An array of annotation stores  # noqa: E501

        :param annotation_stores: The annotation_stores of this PageOfAnnotationStores.
        :type annotation_stores: List[AnnotationStore]
        """
        if annotation_stores is None:
            raise ValueError("Invalid value for `annotation_stores`, must not be `None`")  # noqa: E501

        self._annotation_stores = annotation_stores
