# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.fhir_store import FhirStore
from openapi_server.models.response_page_metadata import ResponsePageMetadata
from openapi_server.models.response_page_metadata_links import ResponsePageMetadataLinks
from openapi_server import util

from openapi_server.models.fhir_store import FhirStore  # noqa: E501
from openapi_server.models.response_page_metadata import ResponsePageMetadata  # noqa: E501
from openapi_server.models.response_page_metadata_links import ResponsePageMetadataLinks  # noqa: E501

class PageOfFhirStores(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=0, limit=10, links=None, total_results=None, fhir_stores=None):  # noqa: E501
        """PageOfFhirStores - a model defined in OpenAPI

        :param offset: The offset of this PageOfFhirStores.  # noqa: E501
        :type offset: int
        :param limit: The limit of this PageOfFhirStores.  # noqa: E501
        :type limit: int
        :param links: The links of this PageOfFhirStores.  # noqa: E501
        :type links: ResponsePageMetadataLinks
        :param total_results: The total_results of this PageOfFhirStores.  # noqa: E501
        :type total_results: int
        :param fhir_stores: The fhir_stores of this PageOfFhirStores.  # noqa: E501
        :type fhir_stores: List[FhirStore]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'links': ResponsePageMetadataLinks,
            'total_results': int,
            'fhir_stores': List[FhirStore]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'links': 'links',
            'total_results': 'totalResults',
            'fhir_stores': 'fhirStores'
        }

        self._offset = offset
        self._limit = limit
        self._links = links
        self._total_results = total_results
        self._fhir_stores = fhir_stores

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfFhirStores':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfFhirStores of this PageOfFhirStores.  # noqa: E501
        :rtype: PageOfFhirStores
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this PageOfFhirStores.

        The index of the first result that must be returned  # noqa: E501

        :return: The offset of this PageOfFhirStores.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PageOfFhirStores.

        The index of the first result that must be returned  # noqa: E501

        :param offset: The offset of this PageOfFhirStores.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501
        if offset is not None and offset < 0:  # noqa: E501
            raise ValueError("Invalid value for `offset`, must be a value greater than or equal to `0`")  # noqa: E501

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this PageOfFhirStores.

        The maximum number of results returned  # noqa: E501

        :return: The limit of this PageOfFhirStores.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PageOfFhirStores.

        The maximum number of results returned  # noqa: E501

        :param limit: The limit of this PageOfFhirStores.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501
        if limit is not None and limit > 100:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `100`")  # noqa: E501
        if limit is not None and limit < 10:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `10`")  # noqa: E501

        self._limit = limit

    @property
    def links(self):
        """Gets the links of this PageOfFhirStores.


        :return: The links of this PageOfFhirStores.
        :rtype: ResponsePageMetadataLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PageOfFhirStores.


        :param links: The links of this PageOfFhirStores.
        :type links: ResponsePageMetadataLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def total_results(self):
        """Gets the total_results of this PageOfFhirStores.

        Total number of results in the result set  # noqa: E501

        :return: The total_results of this PageOfFhirStores.
        :rtype: int
        """
        return self._total_results

    @total_results.setter
    def total_results(self, total_results):
        """Sets the total_results of this PageOfFhirStores.

        Total number of results in the result set  # noqa: E501

        :param total_results: The total_results of this PageOfFhirStores.
        :type total_results: int
        """
        if total_results is None:
            raise ValueError("Invalid value for `total_results`, must not be `None`")  # noqa: E501

        self._total_results = total_results

    @property
    def fhir_stores(self):
        """Gets the fhir_stores of this PageOfFhirStores.

        An array of FHIR stores  # noqa: E501

        :return: The fhir_stores of this PageOfFhirStores.
        :rtype: List[FhirStore]
        """
        return self._fhir_stores

    @fhir_stores.setter
    def fhir_stores(self, fhir_stores):
        """Sets the fhir_stores of this PageOfFhirStores.

        An array of FHIR stores  # noqa: E501

        :param fhir_stores: The fhir_stores of this PageOfFhirStores.
        :type fhir_stores: List[FhirStore]
        """
        if fhir_stores is None:
            raise ValueError("Invalid value for `fhir_stores`, must not be `None`")  # noqa: E501

        self._fhir_stores = fhir_stores
