# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.patient import Patient
from openapi_server import util

from openapi_server.models.patient import Patient  # noqa: E501

class PageOfPatientsAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """PageOfPatientsAllOf - a model defined in OpenAPI

        :param items: The items of this PageOfPatientsAllOf.  # noqa: E501
        :type items: List[Patient]
        """
        self.openapi_types = {
            'items': List[Patient]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfPatientsAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfPatients_allOf of this PageOfPatientsAllOf.  # noqa: E501
        :rtype: PageOfPatientsAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this PageOfPatientsAllOf.

        An array of FHIR Patients  # noqa: E501

        :return: The items of this PageOfPatientsAllOf.
        :rtype: List[Patient]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PageOfPatientsAllOf.

        An array of FHIR Patients  # noqa: E501

        :param items: The items of this PageOfPatientsAllOf.
        :type items: List[Patient]
        """

        self._items = items
