# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.fhir_store import FhirStore
from openapi_server import util

from openapi_server.models.fhir_store import FhirStore  # noqa: E501

class PageOfFhirStoresAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, annotation_stores=None):  # noqa: E501
        """PageOfFhirStoresAllOf - a model defined in OpenAPI

        :param annotation_stores: The annotation_stores of this PageOfFhirStoresAllOf.  # noqa: E501
        :type annotation_stores: List[FhirStore]
        """
        self.openapi_types = {
            'annotation_stores': List[FhirStore]
        }

        self.attribute_map = {
            'annotation_stores': 'annotationStores'
        }

        self._annotation_stores = annotation_stores

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfFhirStoresAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfFhirStores_allOf of this PageOfFhirStoresAllOf.  # noqa: E501
        :rtype: PageOfFhirStoresAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def annotation_stores(self):
        """Gets the annotation_stores of this PageOfFhirStoresAllOf.

        An array of FHIR stores  # noqa: E501

        :return: The annotation_stores of this PageOfFhirStoresAllOf.
        :rtype: List[FhirStore]
        """
        return self._annotation_stores

    @annotation_stores.setter
    def annotation_stores(self, annotation_stores):
        """Sets the annotation_stores of this PageOfFhirStoresAllOf.

        An array of FHIR stores  # noqa: E501

        :param annotation_stores: The annotation_stores of this PageOfFhirStoresAllOf.
        :type annotation_stores: List[FhirStore]
        """

        self._annotation_stores = annotation_stores
