# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.note_store import NoteStore
from openapi_server import util

from openapi_server.models.note_store import NoteStore  # noqa: E501

class PageOfNoteStoresAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """PageOfNoteStoresAllOf - a model defined in OpenAPI

        :param items: The items of this PageOfNoteStoresAllOf.  # noqa: E501
        :type items: List[NoteStore]
        """
        self.openapi_types = {
            'items': List[NoteStore]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfNoteStoresAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfNoteStores_allOf of this PageOfNoteStoresAllOf.  # noqa: E501
        :rtype: PageOfNoteStoresAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this PageOfNoteStoresAllOf.

        An array of note stores  # noqa: E501

        :return: The items of this PageOfNoteStoresAllOf.
        :rtype: List[NoteStore]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PageOfNoteStoresAllOf.

        An array of note stores  # noqa: E501

        :param items: The items of this PageOfNoteStoresAllOf.
        :type items: List[NoteStore]
        """

        self._items = items
