# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.note import Note
from openapi_server import util

from openapi_server.models.note import Note  # noqa: E501

class PageOfNotesAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notes=None):  # noqa: E501
        """PageOfNotesAllOf - a model defined in OpenAPI

        :param notes: The notes of this PageOfNotesAllOf.  # noqa: E501
        :type notes: List[Note]
        """
        self.openapi_types = {
            'notes': List[Note]
        }

        self.attribute_map = {
            'notes': 'notes'
        }

        self._notes = notes

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfNotesAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfNotes_allOf of this PageOfNotesAllOf.  # noqa: E501
        :rtype: PageOfNotesAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notes(self):
        """Gets the notes of this PageOfNotesAllOf.

        An array of notes  # noqa: E501

        :return: The notes of this PageOfNotesAllOf.
        :rtype: List[Note]
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this PageOfNotesAllOf.

        An array of notes  # noqa: E501

        :param notes: The notes of this PageOfNotesAllOf.
        :type notes: List[Note]
        """

        self._notes = notes
