# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.annotation import Annotation
from openapi_server.models.stored_annotation_all_of import StoredAnnotationAllOf
from openapi_server import util

from openapi_server.models.annotation import Annotation  # noqa: E501
from openapi_server.models.stored_annotation_all_of import StoredAnnotationAllOf  # noqa: E501

class StoredAnnotation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, length=None, text=None, note_id=None):  # noqa: E501
        """StoredAnnotation - a model defined in OpenAPI

        :param start: The start of this StoredAnnotation.  # noqa: E501
        :type start: int
        :param length: The length of this StoredAnnotation.  # noqa: E501
        :type length: int
        :param text: The text of this StoredAnnotation.  # noqa: E501
        :type text: str
        :param note_id: The note_id of this StoredAnnotation.  # noqa: E501
        :type note_id: str
        """
        self.openapi_types = {
            'start': int,
            'length': int,
            'text': str,
            'note_id': str
        }

        self.attribute_map = {
            'start': 'start',
            'length': 'length',
            'text': 'text',
            'note_id': 'noteId'
        }

        self._start = start
        self._length = length
        self._text = text
        self._note_id = note_id

    @classmethod
    def from_dict(cls, dikt) -> 'StoredAnnotation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StoredAnnotation of this StoredAnnotation.  # noqa: E501
        :rtype: StoredAnnotation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this StoredAnnotation.

        The position of the first character  # noqa: E501

        :return: The start of this StoredAnnotation.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this StoredAnnotation.

        The position of the first character  # noqa: E501

        :param start: The start of this StoredAnnotation.
        :type start: int
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def length(self):
        """Gets the length of this StoredAnnotation.

        The length of the annotation  # noqa: E501

        :return: The length of this StoredAnnotation.
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this StoredAnnotation.

        The length of the annotation  # noqa: E501

        :param length: The length of this StoredAnnotation.
        :type length: int
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")  # noqa: E501

        self._length = length

    @property
    def text(self):
        """Gets the text of this StoredAnnotation.

        The string annotated  # noqa: E501

        :return: The text of this StoredAnnotation.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this StoredAnnotation.

        The string annotated  # noqa: E501

        :param text: The text of this StoredAnnotation.
        :type text: str
        """

        self._text = text

    @property
    def note_id(self):
        """Gets the note_id of this StoredAnnotation.

        The ID of the note the annotation is from  # noqa: E501

        :return: The note_id of this StoredAnnotation.
        :rtype: str
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id):
        """Sets the note_id of this StoredAnnotation.

        The ID of the note the annotation is from  # noqa: E501

        :param note_id: The note_id of this StoredAnnotation.
        :type note_id: str
        """
        if note_id is None:
            raise ValueError("Invalid value for `note_id`, must not be `None`")  # noqa: E501

        self._note_id = note_id
