# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class StoredAnnotationAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, note_id=None):  # noqa: E501
        """StoredAnnotationAllOf - a model defined in OpenAPI

        :param note_id: The note_id of this StoredAnnotationAllOf.  # noqa: E501
        :type note_id: str
        """
        self.openapi_types = {
            'note_id': str
        }

        self.attribute_map = {
            'note_id': 'noteId'
        }

        self._note_id = note_id

    @classmethod
    def from_dict(cls, dikt) -> 'StoredAnnotationAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StoredAnnotation_allOf of this StoredAnnotationAllOf.  # noqa: E501
        :rtype: StoredAnnotationAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note_id(self):
        """Gets the note_id of this StoredAnnotationAllOf.

        The ID of the note the annotation is from  # noqa: E501

        :return: The note_id of this StoredAnnotationAllOf.
        :rtype: str
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id):
        """Sets the note_id of this StoredAnnotationAllOf.

        The ID of the note the annotation is from  # noqa: E501

        :param note_id: The note_id of this StoredAnnotationAllOf.
        :type note_id: str
        """

        self._note_id = note_id
