# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.date_annotation import DateAnnotation
from openapi_server.models.stored_annotation_all_of import StoredAnnotationAllOf
from openapi_server import util

from openapi_server.models.date_annotation import DateAnnotation  # noqa: E501
from openapi_server.models.stored_annotation_all_of import StoredAnnotationAllOf  # noqa: E501

class StoredDateAnnotation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, length=None, text=None, format=None, note_id=None):  # noqa: E501
        """StoredDateAnnotation - a model defined in OpenAPI

        :param start: The start of this StoredDateAnnotation.  # noqa: E501
        :type start: int
        :param length: The length of this StoredDateAnnotation.  # noqa: E501
        :type length: int
        :param text: The text of this StoredDateAnnotation.  # noqa: E501
        :type text: str
        :param format: The format of this StoredDateAnnotation.  # noqa: E501
        :type format: str
        :param note_id: The note_id of this StoredDateAnnotation.  # noqa: E501
        :type note_id: str
        """
        self.openapi_types = {
            'start': int,
            'length': int,
            'text': str,
            'format': str,
            'note_id': str
        }

        self.attribute_map = {
            'start': 'start',
            'length': 'length',
            'text': 'text',
            'format': 'format',
            'note_id': 'noteId'
        }

        self._start = start
        self._length = length
        self._text = text
        self._format = format
        self._note_id = note_id

    @classmethod
    def from_dict(cls, dikt) -> 'StoredDateAnnotation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StoredDateAnnotation of this StoredDateAnnotation.  # noqa: E501
        :rtype: StoredDateAnnotation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this StoredDateAnnotation.

        The position of the first character  # noqa: E501

        :return: The start of this StoredDateAnnotation.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this StoredDateAnnotation.

        The position of the first character  # noqa: E501

        :param start: The start of this StoredDateAnnotation.
        :type start: int
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def length(self):
        """Gets the length of this StoredDateAnnotation.

        The length of the annotation  # noqa: E501

        :return: The length of this StoredDateAnnotation.
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this StoredDateAnnotation.

        The length of the annotation  # noqa: E501

        :param length: The length of this StoredDateAnnotation.
        :type length: int
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")  # noqa: E501

        self._length = length

    @property
    def text(self):
        """Gets the text of this StoredDateAnnotation.

        The string annotated  # noqa: E501

        :return: The text of this StoredDateAnnotation.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this StoredDateAnnotation.

        The string annotated  # noqa: E501

        :param text: The text of this StoredDateAnnotation.
        :type text: str
        """

        self._text = text

    @property
    def format(self):
        """Gets the format of this StoredDateAnnotation.

        Date format (ISO 8601)  # noqa: E501

        :return: The format of this StoredDateAnnotation.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this StoredDateAnnotation.

        Date format (ISO 8601)  # noqa: E501

        :param format: The format of this StoredDateAnnotation.
        :type format: str
        """

        self._format = format

    @property
    def note_id(self):
        """Gets the note_id of this StoredDateAnnotation.

        The ID of the note the annotation is from  # noqa: E501

        :return: The note_id of this StoredDateAnnotation.
        :rtype: str
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id):
        """Sets the note_id of this StoredDateAnnotation.

        The ID of the note the annotation is from  # noqa: E501

        :param note_id: The note_id of this StoredDateAnnotation.
        :type note_id: str
        """
        if note_id is None:
            raise ValueError("Invalid value for `note_id`, must not be `None`")  # noqa: E501

        self._note_id = note_id
