# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TextPhysicalAddressAnnotationAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, length=None, text=None, type=None):  # noqa: E501
        """TextPhysicalAddressAnnotationAllOf - a model defined in OpenAPI

        :param start: The start of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :type start: int
        :param length: The length of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :type length: int
        :param text: The text of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :type text: str
        :param type: The type of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'start': int,
            'length': int,
            'text': str,
            'type': str
        }

        self.attribute_map = {
            'start': 'start',
            'length': 'length',
            'text': 'text',
            'type': 'type'
        }

        self._start = start
        self._length = length
        self._text = text
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'TextPhysicalAddressAnnotationAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextPhysicalAddressAnnotation_allOf of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :rtype: TextPhysicalAddressAnnotationAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this TextPhysicalAddressAnnotationAllOf.

        The position of the first character  # noqa: E501

        :return: The start of this TextPhysicalAddressAnnotationAllOf.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this TextPhysicalAddressAnnotationAllOf.

        The position of the first character  # noqa: E501

        :param start: The start of this TextPhysicalAddressAnnotationAllOf.
        :type start: int
        """

        self._start = start

    @property
    def length(self):
        """Gets the length of this TextPhysicalAddressAnnotationAllOf.

        The length of the annotation  # noqa: E501

        :return: The length of this TextPhysicalAddressAnnotationAllOf.
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this TextPhysicalAddressAnnotationAllOf.

        The length of the annotation  # noqa: E501

        :param length: The length of this TextPhysicalAddressAnnotationAllOf.
        :type length: int
        """

        self._length = length

    @property
    def text(self):
        """Gets the text of this TextPhysicalAddressAnnotationAllOf.

        The string annotated  # noqa: E501

        :return: The text of this TextPhysicalAddressAnnotationAllOf.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this TextPhysicalAddressAnnotationAllOf.

        The string annotated  # noqa: E501

        :param text: The text of this TextPhysicalAddressAnnotationAllOf.
        :type text: str
        """

        self._text = text

    @property
    def type(self):
        """Gets the type of this TextPhysicalAddressAnnotationAllOf.

        Type of address information  # noqa: E501

        :return: The type of this TextPhysicalAddressAnnotationAllOf.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TextPhysicalAddressAnnotationAllOf.

        Type of address information  # noqa: E501

        :param type: The type of this TextPhysicalAddressAnnotationAllOf.
        :type type: str
        """
        allowed_values = ["city", "country", "department", "hospital", "organization", "other", "room", "state", "street", "zip"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
