# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TextPhysicalAddressAnnotationAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address_type=None):  # noqa: E501
        """TextPhysicalAddressAnnotationAllOf - a model defined in OpenAPI

        :param address_type: The address_type of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :type address_type: str
        """
        self.openapi_types = {
            'address_type': str
        }

        self.attribute_map = {
            'address_type': 'addressType'
        }

        self._address_type = address_type

    @classmethod
    def from_dict(cls, dikt) -> 'TextPhysicalAddressAnnotationAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextPhysicalAddressAnnotation_allOf of this TextPhysicalAddressAnnotationAllOf.  # noqa: E501
        :rtype: TextPhysicalAddressAnnotationAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_type(self):
        """Gets the address_type of this TextPhysicalAddressAnnotationAllOf.

        Type of address information  # noqa: E501

        :return: The address_type of this TextPhysicalAddressAnnotationAllOf.
        :rtype: str
        """
        return self._address_type

    @address_type.setter
    def address_type(self, address_type):
        """Sets the address_type of this TextPhysicalAddressAnnotationAllOf.

        Type of address information  # noqa: E501

        :param address_type: The address_type of this TextPhysicalAddressAnnotationAllOf.
        :type address_type: str
        """
        allowed_values = ["city", "country", "department", "hospital", "organization", "other", "room", "state", "street", "zip"]  # noqa: E501
        if address_type not in allowed_values:
            raise ValueError(
                "Invalid value for `address_type` ({0}), must be one of {1}"
                .format(address_type, allowed_values)
            )

        self._address_type = address_type
