# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.text_annotation import TextAnnotation
from openapi_server.models.text_id_annotation_all_of import TextIdAnnotationAllOf
from openapi_server import util

from openapi_server.models.text_annotation import TextAnnotation  # noqa: E501
from openapi_server.models.text_id_annotation_all_of import TextIdAnnotationAllOf  # noqa: E501

class TextIdAnnotation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, length=None, text=None, confidence=None, id_type=None):  # noqa: E501
        """TextIdAnnotation - a model defined in OpenAPI

        :param start: The start of this TextIdAnnotation.  # noqa: E501
        :type start: int
        :param length: The length of this TextIdAnnotation.  # noqa: E501
        :type length: int
        :param text: The text of this TextIdAnnotation.  # noqa: E501
        :type text: str
        :param confidence: The confidence of this TextIdAnnotation.  # noqa: E501
        :type confidence: float
        :param id_type: The id_type of this TextIdAnnotation.  # noqa: E501
        :type id_type: str
        """
        self.openapi_types = {
            'start': int,
            'length': int,
            'text': str,
            'confidence': float,
            'id_type': str
        }

        self.attribute_map = {
            'start': 'start',
            'length': 'length',
            'text': 'text',
            'confidence': 'confidence',
            'id_type': 'idType'
        }

        self._start = start
        self._length = length
        self._text = text
        self._confidence = confidence
        self._id_type = id_type

    @classmethod
    def from_dict(cls, dikt) -> 'TextIdAnnotation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextIdAnnotation of this TextIdAnnotation.  # noqa: E501
        :rtype: TextIdAnnotation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this TextIdAnnotation.

        The position of the first character  # noqa: E501

        :return: The start of this TextIdAnnotation.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this TextIdAnnotation.

        The position of the first character  # noqa: E501

        :param start: The start of this TextIdAnnotation.
        :type start: int
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def length(self):
        """Gets the length of this TextIdAnnotation.

        The length of the annotation  # noqa: E501

        :return: The length of this TextIdAnnotation.
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this TextIdAnnotation.

        The length of the annotation  # noqa: E501

        :param length: The length of this TextIdAnnotation.
        :type length: int
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")  # noqa: E501

        self._length = length

    @property
    def text(self):
        """Gets the text of this TextIdAnnotation.

        The string annotated  # noqa: E501

        :return: The text of this TextIdAnnotation.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this TextIdAnnotation.

        The string annotated  # noqa: E501

        :param text: The text of this TextIdAnnotation.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def confidence(self):
        """Gets the confidence of this TextIdAnnotation.

        The confidence in the accuracy of the annotation  # noqa: E501

        :return: The confidence of this TextIdAnnotation.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this TextIdAnnotation.

        The confidence in the accuracy of the annotation  # noqa: E501

        :param confidence: The confidence of this TextIdAnnotation.
        :type confidence: float
        """
        if confidence is None:
            raise ValueError("Invalid value for `confidence`, must not be `None`")  # noqa: E501
        if confidence is not None and confidence > 100:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value less than or equal to `100`")  # noqa: E501
        if confidence is not None and confidence < 0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0`")  # noqa: E501

        self._confidence = confidence

    @property
    def id_type(self):
        """Gets the id_type of this TextIdAnnotation.

        Type of ID information  # noqa: E501

        :return: The id_type of this TextIdAnnotation.
        :rtype: str
        """
        return self._id_type

    @id_type.setter
    def id_type(self, id_type):
        """Sets the id_type of this TextIdAnnotation.

        Type of ID information  # noqa: E501

        :param id_type: The id_type of this TextIdAnnotation.
        :type id_type: str
        """
        allowed_values = ["account", "bio_id", "device", "health_plan", "id_number", "license", "medical_record", "ssn", "vehicle", "other"]  # noqa: E501
        if id_type not in allowed_values:
            raise ValueError(
                "Invalid value for `id_type` ({0}), must be one of {1}"
                .format(id_type, allowed_values)
            )

        self._id_type = id_type
