# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Text(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None):  # noqa: E501
        """Text - a model defined in OpenAPI

        :param text: The text of this Text.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'text': str
        }

        self.attribute_map = {
            'text': 'text'
        }

        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'Text':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Text of this Text.  # noqa: E501
        :rtype: Text
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this Text.

        A text  # noqa: E501

        :return: The text of this Text.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Text.

        A text  # noqa: E501

        :param text: The text of this Text.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
